POST   http://localhost:3000/api/feedback
Content-Type: application/json

{
    "CustomerID":"67adb7d12b8ed3a359f1bcb9",
    "ProductID":"",
    "Rating":5
}

###
GET  http://localhost:3000/api/feedback