import { z } from 'zod';
import { extendZod, zId } from "@zodyac/zod-mongoose";

// Extend zod with the zId and zUUID functions (!!important)
extendZod(z); 

// Define the schema (!!important)
export const RoutineProductSchema = z.object({
    product_id: zId("Product"),
    step_number: z.number().min(0),
    //default value will be generated by mongoose
    createdAt: z.date().default(new Date()), 
    updatedAt: z.date().default(new Date()),
});


// Define the schema with the ID (!!important)
export const zRoutineProductSchemaUdate = RoutineProductSchema.extend({
    _id: zId(), //default value will be generated by mongoose
})

export type RoutineProduct = z.infer<typeof zRoutineProductSchemaUdate>;