import { z } from 'zod';
import { extendZod, zId } from "@zodyac/zod-mongoose";

// Extend zod with the zId and zUUID functions (!!important)
extendZod(z); 

// Define the schema (!!important)
export const SkinTypeSchema = z.object({
    name: z.string().min(3).max(20).default("test"),
    description: z.string().min(3).max(2000).default("test"),
    //default value will be generated by mongoose
    createdAt: z.date().default(new Date()), 
    updatedAt: z.date().default(new Date()),
});


// Define the schema with the ID (!!important)
export const zSkinTypeSchemaUdate = SkinTypeSchema.extend({
    _id: zId(), //default value will be generated by mongoose
})

export type SkinType = z.infer<typeof SkinTypeSchema>;