import type React from "react"
import type { Metadata } from "next"
import { Lexend } from "next/font/google"
import "./globals.css"
import { ThemeProvider } from "@/components/theme-provider"
import { SidebarProvider } from "@/components/ui/sidebar"
import { AdminSidebar } from "@/components/staff/admin-sidebar"


const LexendSans = Lexend({ subsets: ['latin', 'latin-ext', 'vietnamese'] });

export const metadata: Metadata = {
  title: {
    template: '%s | Skincare',
    default: 'Skincare', // a default is required when creating a template
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="vi" suppressHydrationWarning={true}>
      <body
        className={`${LexendSans.className} antialiased flex flex-col min-h-full`}
      >
        <div className=" absolute inset-0">
          <ThemeProvider attribute="class" defaultTheme="light" enableSystem disableTransitionOnChange>
            <SidebarProvider>
              <div className="flex min-h-screen w-full">
                <AdminSidebar />
                <section className="flex-1 w-0 min-w-0 overflow-y-auto">
                  <main className="container mx-auto">{children}</main>
                </section>
              </div>
            </SidebarProvider>
            <div className="fixed inset-0 -z-10 h-full w-full bg-[linear-gradient(to_right,#f0f0f0_1px,transparent_1px),linear-gradient(to_bottom,#f0f0f0_1px,transparent_1px)] bg-[size:6rem_4rem]"/>
          </ThemeProvider>
        </div>
      </body>
    </html>
  )
}

